keys:
  # Users
  - &user1 A46FA202C57484D61B5B644457FEA671DEEEEA14
  # Hosts
  - &farosh age1u2sp6r7gyjddkvx397n3rmaylx7a8ckk33zmvpn6j56g23edketqgnzzg9

creation_rules:
  # - path_regex: hosts/dinraal/secrets.ya?ml$
  #   key_groups:
  #     pgp:
  #       - *user1
  - path_regex: hosts/farosh/secrets.ya?ml$
    key_groups:
      - pgp:
          - *user1
      - age:
          - *farosh
  - path_regex: users/secrets.ya?ml$
    key_groups:
      - age:
          - *farosh
      - pgp:
          - *user1
